"""transaction_tool

Revision ID: 01_486ccb90c88a
Revises:
Create Date: 2025-07-09 18:47:58.631767

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01_486ccb90c88a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_tool",
        sa.Column("verification_code_id", sa.Integer(), nullable=False),
        sa.Column("private_key", sa.LargeBinary(), nullable=False),
        sa.Column("verification_code", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_tool_verification_code"),
        "transaction_tool",
        ["verification_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_tool_verification_code_id"),
        "transaction_tool",
        ["verification_code_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transaction_tool_verification_code_id"), table_name="transaction_tool"
    )
    op.drop_index(
        op.f("ix_transaction_tool_verification_code"), table_name="transaction_tool"
    )
    op.drop_table("transaction_tool")
    # ### end Alembic commands ###
